name: "Jacked Scan"
description: "Jacked provides organizations with a more comprehensive look at their application to take calculated actions and create a better security approach. Its primary purpose is to scan vulnerabilities to implement subsequent risk mitigation measures."
author: "Carbonetes"
inputs:
runs:
  